[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "public/img", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
  ]
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[functions]
  node_bundler = "esbuild"